uktrade/strategic-companies-list

.gitignore
README.md
index.html
package-lock.json
package.json

This is just a copy of the default page from the GOV.UK Design System docs.

feat: initial mockup page and ability to look at it locally

---

index.html

Very provisional, but it is the best we have for now

feat: initial name of service as Strategic Companies List

---

index.html

This is both for users to take care, but also to as a small signifier of trust in the system.

feat: mark as official sensitive

---

index.html

And using the words granted and privileged to make it clear not everyone has access

feat: sections for content, with your things at the top

---

index.html

It's apparently the more usual term

feat: rename events to engagements

---

index.html

It looks a bit odd - feels better to be consistent on the link colours.

feat: no visited style on Past enagements link

---

index.html

Since it's capitalised, it was looking a bit big

feat: smaller text in tag

---

index.html

It looks a bit more like a "stamp" now, which is good.

feat: bold tag and smaller

---

Dockerfile

This is to be able to fire this up in ECS (at least, a step towards that)

chore: basic Dockerfile

---

Dockerfile

This is the actual mockup so far, so pretty crucial

fix: include index.html in Dockerfile

---

index.html

This is how it was before - I accidentally increased it

feat: less padding on desktop panels

---

CODEOWNERS

It's too early in the project to enforce reviews by Data Infrastructure I think

chore: limit reviews needed by Data Infrastructure

---

index.html

feat: ignore spaces company search

---

index.html

This might not make too much of a difference with real company names, but every bit helps

feat: search by matching each word

---

infra/1-variables.tf
infra/7-codebuild.tf

Not the fanciest thing in the world, but it works enough for now

infra: initial CodeBuild project for deployment

---

README.md
infra/Ω-output.tf

To make it slightly easier to create the right DNS records

infra: output the ALB DNS name

---

Dockerfile
nginx.conf
scl/settings.py
scl/urls.py
start.sh

Also avoids running the server as root

infra: use nginx to serve static files

---

Dockerfile
browser.js
package-lock.json
package.json
scl/core/templates/base.html
scl/core/templates/engagement.html
scl/core/views.py
scl/urls.py
webpack.config.js

And since no creds, this won't actually work (it will if you hard code the creds, but we can't do that when deployed)

feat: initial/rough recording UI, but no creds

---

browser.js
infra/6-ecs.tf

There was an error in the JS, and with IAM policies

fix: engagement transcription

---

nginx.conf

- Groups options a bit more nicely
- Enables tcp_nopush
- Hopefully _really_ enables keepalive to the backend (suspect this was attempted before, but didn't actually work)

chore: tidy and slightly optimse nginx config

---

browser.js
scl/core/templates/base.html
scl/core/templates/engagement.html
scl/core/templates/index.html

No nice animation when it's recording for now

feat: transcription on front page

---

scl/core/templates/base.html
scl/core/templates/company.html

This adds some more content and layout changes

feat: layout updates

---

scl/core/templates/base.html
scl/core/templates/index.html

This makes then take up less space and also better align when there are several of them

feat: put dates in tags

---

scl/core/templates/base.html
scl/core/templates/company.html

This change adds some layout changes and proposes tags to the areas that are private to the user.

Feat: layout changes and split sections into card components

---

scl/core/templates/base.html
scl/core/templates/company.html

This change allows the user to see what an inline edit UX could look like.

feat: add edit functionality and styling

---

scl/core/templates/base.html
scl/core/templates/company.html

Moved to flex rather than grid (admittedly partially because I'm more familiar with it)

feat: edit and print on the same line

---

scl/core/templates/base.html
scl/core/templates/company.html

So there is less padding taken up in general

feat: no cards on company page

---

scl/core/templates/base.html
scl/core/templates/company.html

I'm not amazingly happy with it, but I hope a step forward from before. Depends maybe too much on it being smaller text...

feat: tidier company sidebar

---

scl/core/templates/company.html

To make it clear what the privileged tag applies to

feat: increase space above priorities

---

scl/core/static/scl.css
scl/core/templates/base.html
scl/core/templates/index.html

And a bit simpler without the extra HTML element

refactor: search input CSS to BEM

---

scl/core/templates/company.html

feat: show account managers to unprivileged users

---

requirements.in
requirements.txt
scl/settings.py

We store the session in the database, so it might save 1ms or so on each request?

perf: enable database connection pooling

---

requirements.in
requirements.txt

The code in the branch has now been released

build(deps): use released django-staff-sso-client

---

scl/core/templates/company.html
scl/core/views.py

fix: restore/revert company page

---

scl/core/api/v1/company.py
scl/core/templates/company_briefing.html
scl/core/views.py
scl/urls.py

This change abstracts the API view out of the HTML view.

refactor: move api view out of html view

---

scl/core/api/v1/company.py
scl/core/templates/company.html
scl/core/views.py
scl/urls.py

Using the hard coded data as essentially the default

feat: working edit of HMG and Company priorities

---

compose.yaml
scl/core/templates/company.html
scl/core/templates/company_briefing.html
scl/core/templates/engagements.html
scl/core/views.py
scl/urls.py

This change is the start of the engagements page

feat: add engagement page

---

scl/core/api/v1/company.py

It's all HTML, so it shouldn't matter

perf: trim string when saving

---

scl/core/api/v1/engagement.py
scl/core/static/scl.css
scl/core/templates/base.html
scl/core/templates/company.html
scl/core/templates/engagements.html
scl/urls.py

This change allows the user to edit the engagements page.

feat: make engagements editable

---

scl/core/templates/index.html

Quick indicator if all the right ones are there

feat: include number of companies on the front page

---

compose.yaml
infra/09-ecs-and-transcribe.tf
scl/core/middleware.py
scl/core/templates/403_ip_filter.html
scl/settings.py

Essentially so we can show a nicer error message to users

feat: in-app IP filter

---

scl/core/management/commands/creategroups.py
start-dev.sh
start.sh

The start of more of a permissions model in the app

feat: add basic access group

---

scl/core/constants.py
scl/core/management/commands/creategroups.py
scl/core/middleware.py
scl/core/templates/403_basic_access.html
scl/settings.py

This is so permissions can be controlled within the app itself

feat: enforce group membership to get access

---

compose.yaml
scl/core/forms.py
scl/core/static/scl.css
scl/core/templates/add_engagements.html
scl/core/templates/company.html
scl/core/views/html.py
scl/settings.py
scl/urls.py

This change allows the user to post new engagements against a company.

feat: add engagement form

---

scl/core/templates/all_engagements.html
scl/core/templates/company.html
scl/core/views/html.py
scl/urls.py

This change adds a company engagements page that lists all past and present engagements.

feat: add company engagements page

---

scl/core/templates/company.html
scl/core/templates/engagements.html

This change updates the breadcrumb for some pages.

fix: update breadcrumb

---

scl/core/templates/company_engagements.html
scl/core/views/html.py

This change fixes the upcoming and past engagements lists.

fix: correct the past and present lists

---

Dockerfile
compose-vde.yaml
scl/settings.py
scl/settings_vde.py

* port forwarding setup requires SESSION_COOKIE_SECURE = False and SESSION_COOKIE_DOMAIN = None
* vde build/create/start via `docker compose -f compose-vde.yaml up --build`

feat: aws workspace vde compatible

---

scl/core/static/scl.js
scl/core/templates/base.html
scl/core/templates/company.html
scl/core/templates/company_engagements.html
scl/core/templates/engagements.html
scl/core/templates/partials/header.html
scl/core/templates/your_engagements.html
scl/core/views/api.py
scl/core/views/html.py

This change consolidates HTML and extracts the JS into an external file

refactor: consolidate header HTML and move JS to external file

---

scl/core/static/scl.js
scl/core/templates/base.html
scl/core/templates/partials/header.html

Currently we are not posting the CSRF token when saving the transcript.

fix: token post

---

scl/core/static/scl.css
scl/core/static/scl.js
scl/core/templates/company.html
scl/core/templates/engagements.html
scl/core/templates/partials/header.html
scl/core/views/api.py

This change allows the user to edit the notes.

feat: make notes editable and remove delete

---

scl/core/templates/partials/header.html

Reverts uktrade/strategic-companies-list#286

Revert "fix: header layout"

---

scl/core/templates/company.html

Reverts uktrade/strategic-companies-list#284

Revert "fix: re-select elements for toggling edit mode"

---

scl/core/templates/company.html

Reverts uktrade/strategic-companies-list#283

Revert "fix: add to existing priority list"

---

scl/core/templates/company.html

Reverts uktrade/strategic-companies-list#282

Revert "fix: last updated dates and hidden fields"

---

scl/core/templates/company.html
scl/core/templates/partials/header.html
scl/core/views/api.py

Reverts uktrade/strategic-companies-list#281

Revert "fix: sticky company name and gb dates format"

---

Dockerfile

This change will make sure static assets are built and copied correctly.

fix: make sure static assets are built and copied correctly

---

scl/core/static/react/components/forms/company-priorites/Update.jsx
scl/core/static/react/features/company-briefing/CompanyPriorities.jsx

This change fixes up a typo, adds some content and removes buttons when the user isn't editing it.

fix: typo and hide form buttons

---

package-lock.json
scl/core/static/react/features/company-briefing/CompanyDetails.jsx
scl/core/static/react/features/company-briefing/KeyPeople.jsx
scl/core/static/react/features/company-briefing/Page.jsx
scl/core/static/react/features/company-briefing/Priorities.jsx
scl/core/static/react/forms/company-details/Update.jsx
scl/core/static/react/forms/key-people/Update.jsx
scl/core/views/api.py
scl/core/views/html.py

This change allows the user to edit the company title

feat: add editable company title

---

scl/core/sass/components/breadcrumb.scss
scl/core/sass/components/header-actions.scss
scl/core/sass/components/page-header.scss
scl/core/sass/print.scss
scl/core/sass/scl.scss
scl/core/static/react/components/Breadcrumb.jsx
scl/core/static/react/components/PageActions.jsx
scl/core/static/react/features/company-briefing/AccountManagers.jsx
scl/core/static/react/features/company-briefing/KeyFacts.jsx
scl/core/static/react/features/company-briefing/Page.jsx
scl/core/static/react/features/company-briefing/RecentTopLevelEngagements.jsx
scl/core/templates/company.html
scl/core/views/html.py

This change hides privileged data, updates styles and adds print functionality.

fix: updates header styles and guards privileged data

---

scl/core/sass/components/notification.scss
scl/core/sass/scl.scss
scl/core/static/react/components/NotificationBanner.jsx
scl/core/static/react/features/company-briefing/CompanyDetails.jsx
scl/core/static/react/features/company-briefing/KeyPeople.jsx
scl/core/static/react/features/company-briefing/Page.jsx
scl/core/static/react/features/company-briefing/Priorities.jsx

This change adds a notification banner that shows every time the user edits and updates data.

feat: add notifications

---

requirements.in
requirements.txt
scl/core/static/react/constants.js
scl/core/static/react/features/engagement/Notes.jsx
scl/core/static/react/features/engagement/Page.jsx
scl/core/static/react/forms/notes/Create.jsx
scl/core/static/react/mount.jsx
scl/core/static/react/providers.js
scl/core/templates/base.html
scl/core/templates/index.html
scl/core/views/api.py
scl/core/views/html.py
scl/core/views/utils.py
scl/settings.py

This change adds the waffle library for feature flagging and feature flags the AWS transcribe.

feat: add waffle and feature flag aws transcribe

---

scl/core/fixtures/e2e-fixtures.json

Sets up initial end-to-end fixtures to support testing from a user's perspective.

Add e2e fixtures

---

conftest.py
scl/core/management/commands/createtestdata.py
scl/core/tests/factories.py
scl/core/tests/test_commands.py

Usage:
`./manage.py createtestdata "your.local.user.email@example.com" 100`
Output:

Add createtestdata management command

---

.github/workflows/tests.yml
Makefile
compose.e2e.yaml
cypress.config.js
cypress/e2e/spec.cy.js
cypress/support/commands.js
cypress/support/e2e.js
package-lock.json
package.json

This change adds the following
- Updates actions to use the e2e compose file
- Adds testing library to the Cypress command
- Runs a test against the fixture data

feat: Set up CI pipeline to run Cypress E2E tests

---

cypress.config.js
cypress/e2e/company.cy.js
cypress/e2e/fixtures.js
cypress/e2e/spec.cy.js

Add initial company briefing E2E tests (inside the red box)

Add initial company briefing E2E tests

---

cypress/e2e/company.cy.js
cypress/support/assertions.js
scl/core/static/react/forms/engagements/Create.jsx

Adding E2E tests around adding an engagement.

test: adding an engagement (E2E)

---

scl/core/templates/base.html

This adds the GA tag manager scripts to all pages of the app.

feat: add GA tag manager script

---

scl/core/sass/components/recording-animation.scss
scl/core/sass/scl.scss
scl/core/templates/base.html
scl/core/templates/icons/recording.svg.html
scl/settings.py

This corrects the wrong implementation of GA which was done here #362. Also this updates CSP settings to work correctly with Google Tag manager.

feat: add google tag manager

---

cypress/e2e/company.cy.js
cypress/support/assertions.js
scl/context_processors.py
scl/core/static/react/components/Section.jsx
scl/core/static/react/features/company-briefing/AccountManagers.jsx
scl/core/static/react/features/company-briefing/CompanyDetails.jsx
scl/core/static/react/features/company-briefing/Engagements.jsx
scl/core/static/react/features/company-briefing/Page.jsx
scl/core/static/react/features/company-briefing/Priorities.jsx
scl/core/static/react/features/engagement/Details.jsx
scl/core/static/react/features/engagement/Page.jsx
scl/core/templates/base.html
scl/core/templates/index.html
scl/settings.py

This change addresses some last minute issues and content updates:
1. When the engagement is updated the title now updates automatically
2. General content updates addressed
3. Bug fixed around updating the company details
4. Removed privileged tags
5. CSP updated to allow React multi select to function
6. If the environment is not production then we now hide Google tag manager

fix: Content updates and bug fixes

---

scl/settings.py

This change adds the Sentry performance tracing to the config.

feat: add sentry performance

---

cypress/e2e/home.cy.js
cypress/e2e/spec.cy.js
scl/core/templates/index.html
scl/core/tests/test_views_home.py
scl/core/views/api.py

This change updates some content on the home page.

refactor: update home page content

---

scl/core/static/react/components/NotificationBanner.jsx
scl/core/static/react/features/company-briefing/AddEngagement.jsx
scl/core/static/react/features/company-briefing/CompanyDetails.jsx
scl/core/static/react/features/company-briefing/KeyPeople.jsx
scl/core/static/react/features/company-briefing/Page.jsx
scl/core/static/react/features/company-briefing/Priorities.jsx
scl/core/static/react/features/company-briefing/Summary.jsx
scl/core/static/react/features/engagement/Details.jsx
scl/core/static/react/features/engagement/Notes.jsx
scl/core/views/api.py
scl/settings.py

This change updates the notification messages on error and returns json when there is an issue with the CSRF token.

feat: handle csrf failure with json response

---

cypress/e2e/company-briefing.cy.js
scl/core/static/react/forms/notes/Create.jsx

SCL-186: Update note form styling

---

conftest.py
scl/core/management/commands/creategroups.py
scl/core/tests/test_api.py
scl/core/tests/test_company_briefing.py
scl/core/tests/test_views_engagement.py
scl/core/views/api.py
scl/core/views/html.py
scl/settings.py
start-dev.sh
start-e2e.sh

This change adds a new access group called "Super access". This can be given to selected users who need global access to edit all company data.

feat: add super access group

---

scl/core/static/react/features/company-briefing/Engagements.jsx

Might be a good idea to revisit the css at some point.

rejig margins etc on company page design
